[Service]
User=rupal
Group=rupal
PrivateUsers=no
PrivateTmp=no
ProtectHome=no
Environment="XDG_RUNTIME_DIR=/run/user/1000"
Environment="PIPEWIRE_REMOTE=pipewire-0"
Environment="PULSE_SERVER=unix:/run/user/1000/pulse/native"
Environment="LIBRESPOT_BACKEND=pulseaudio"
Environment="LIBRESPOT_VOLUME_CTRL=linear"
Environment="LIBRESPOT_INITIAL_VOLUME=100"
Restart=on-failure
RestartSec=5

[Unit]
StartLimitIntervalSec=0
