[*]
wallpaper_mode=center
wallpaper_common=1
wallpaper=/home/rupal/Pictures/pinet-logo-wallpaper.png
desktop_bg=#14161a
desktop_fg=#e8e8e8
desktop_shadow=#d6d3de
desktop_font=Nunito Sans Light 10
show_wm_menu=0
sort=name;ascending;
show_documents=0
show_home=0
show_trash=0
show_mounts=0

[pinet.desktop]
x=30
y=30

[spotify.desktop]
x=30
y=130

[eth-share.desktop]
x=30
y=230

[pinet-board.desktop]
x=30
y=330

[camera-kiosk.desktop]
x=160
y=30

[ezykam-kiosk.desktop]
x=160
y=130

[photo-frame.desktop]
x=160
y=230

[Slideshow Photos]
x=160
y=330

[PINET-Media]
x=160
y=430

[kali-tools.desktop]
x=290
y=30

[graphs.desktop]
x=290
y=130

[kali-tools-guide.txt]
x=290
y=330
