[*]
wallpaper_mode=center
wallpaper_common=1
wallpaper=/home/rupal/Pictures/pinet-logo-wallpaper.png
desktop_bg=#14161a
desktop_fg=#e8e8e8
desktop_shadow=#d6d3de
desktop_font=Nunito Sans Light 10
show_wm_menu=0
sort=mtime;ascending;
show_documents=0
show_home=0
show_trash=1
show_mounts=0

[pinet-start.desktop]
x=20
y=14

[pinet-stop.desktop]
x=20
y=100

[pinet-board.desktop]
x=20
y=186

[PINET-Media]
x=20
y=272

[photo-frame.desktop]
x=140
y=14

[Slideshow Photos]
x=140
y=100

[camera-kiosk.desktop]
x=140
y=186

[ezykam-kiosk.desktop]
x=140
y=272

[lock-screen.desktop]
x=660
y=14

[kali-tools.desktop]
x=660
y=110

[kali-tools-guide.txt]
x=660
y=196
